### ISSUE TITLE
Implement dir and dirxml command

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#244]
The command line should offer the [`dir()`](http://getfirebug.com/wiki/index.php/Dir) and [`dirxml()`](http://getfirebug.com/wiki/index.php/Dirxml) commands.

Platform API: search for "JSTermHelpers"

Honza

**Comment by fflorent** [comment]
They probably can be aliased to `console.dir[xml]`, which are existant in the DevTools.

I am taking this one, as it is probably the simplest to implement, and it would introduce the registration logic. Thus it would pave the way for the other commands and maybe for some Firebug SDK methods.

Florent

**Comment by fflorent** [comment]
Above is the work in progress. Some comments/questions:
  * `dirxml` won't do anything. Because `console.dirxml()` is not implemented yet. See [bug 922212](https://bugzilla.mozilla.org/show_bug.cgi?id=922212)
  * `dir` works in when not using E10S. When using E10S, you need to (otherwise, dir is not defined, and I don't know why):
      1.  open a new tab
      2. close the previous tab
      3. Open the DevTools and run `dir(whatEverYouWant)`
  * As explained [here](https://github.com/firebug/firebug.next/commit/8119c51fe7566e85de8cf50bfab245e203cae016#diff-670bfa8c8deeee0a6f17d2b3f0990234R59), I don't know what to choose between a tab or a global actor (I would say global ; thoughts?). But choosing a global actor doesn't work with E10S. Any idea why?

Florent

**Comment by fflorent** [comment]
@janodvarko Could you give me some feedback please (especially for point 2 and 3 of the previous comment)?

Thanks in advance

Florent

**Comment by fflorent** [comment]
ping @janodvarko ?

Florent

**Comment by janodvarko** [comment]
@fflorent: sorry for the delay

>  add 2) dir works in when not using E10S. When using E10S, you need to (otherwise, dir is not defined, and I don't know why): 

This might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1155168
I attached a platform patch, so you might want to try it out and see if it helps.

> add 3) As explained here, I don't know what to choose between a tab or a global actor

If I understand correctly your commands are using the current window
```
owner.window.console.dir(...args);
```

so, you need to run in the child process (the same process as the tab/window), so Tab actor is the right choice here.

Honza

**Comment by fflorent** [comment]
> This might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1155168
I attached a platform patch, so you might want to try it out and see if it helps.

Weird, I can't tell why, but I can't reproduce the issue, even without the patch. Let's say it works.....

> so, you need to run in the child process (the same process as the tab/window), so Tab actor is the right choice here.

Thanks for the explanation. 

So I guess the patch is ready for a review.

Florent

**Comment by janodvarko** [comment]
> So I guess the patch is ready for a review.

I did couple of comments.
I think that you can commit as soon as it's resolved.

Honza

**Comment by fflorent** [comment]
All done 8236509

I wonder if we shouldn't somehow use trait, so the frontend knows whether the backend implements the WebConsoleCommands API:
https://dxr.mozilla.org/mozilla-central/source/toolkit/devtools/server/actors/root.js#110

Florent

**Comment by janodvarko** [comment]
> All done 8236509

Excellent

> I wonder if we shouldn't somehow use trait, so the frontend knows whether the backend implements the WebConsoleCommands API:

Good question, I think bgrins is good start to ask, let me know if you want me to rout you to someone else...

Btw. I am still worried about https://bugzilla.mozilla.org/show_bug.cgi?id=1155168
Is it reproducible with your patch?

Honza

**Comment by fflorent** [comment]
> Good question, I think bgrins is good start to ask, let me know if you want me to rout you to someone else...

Bug reported, patch submitted in [bug 1159009](https://bugzilla.mozilla.org/show_bug.cgi?id=1159009).

> Btw. I am still worried about https://bugzilla.mozilla.org/show_bug.cgi?id=1155168
Is it reproducible with your patch?

Sorry, not sure what you mean. What should be reproducible with my patch? 

Florent

**Comment by janodvarko** [comment]
> > Btw. I am still worried about https://bugzilla.mozilla.org/show_bug.cgi?id=1155168

> Sorry, not sure what you mean. What should be reproducible with my patch? 

Don't worry about this one, I've already fixed it on the platform.
(I just wanted to know if it breaks your patch)

Honza

**Comment by fflorent** [comment]
> Don't worry about this one, I've already fixed it on the platform.
(I just wanted to know if it breaks your patch)

Now, everything works like a charm, even with your patch.

I just added the trait. I will implement the tests (and see why the tests are still failing on Travis).

Florent

**Comment by janodvarko** [comment]
@fflorent what's the status here, should we close this and track the progress in related bugzilla bug?

Honza
